#!/usr/bin/env python3

import argparse
import sys
import os

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)
from piwall2.broadcaster import Broadcaster

def parseArgs():
    parser = argparse.ArgumentParser(description='piwall2 video broadcaster')
    parser.add_argument('--url', dest='url', action='store', default='https://www.youtube.com/watch?v=xmUZ6nCFNoU',
        help='youtube video url. default: The Smashing Pumpkins - Today.')

    args = parser.parse_args()
    return args


args = parseArgs()
Broadcaster(args.url).broadcast()
