#!/usr/bin/env python3

import sys
import argparse
import os
import time

from piwall2.logger import Logger

def parseArgs():
    parser = argparse.ArgumentParser(description='piwall2 delay buffer')
    parser.add_argument('--log-uuid', dest='log_uuid', action='store',
        help='Logger UUID')
    parser.add_argument('--delay', dest='delay_s', action='store', type=int, help='Delay in seconds')
    args = parser.parse_args()
    return args


args = parseArgs()
log_level = Logger.get_level()
if args.log_uuid:
    Logger.set_uuid(args.log_uuid)

logger = Logger(dont_log_to_stdout = True).set_namespace(os.path.basename(__file__))
logger.info("Starting delay_buffer...")

start = time.time()
buffer = b''
while True:
    data = sys.stdin.buffer.read(4096)
    is_delay_over = (time.time() - start) > args.delay_s
    if is_delay_over:
        if buffer:
            sys.stdout.buffer.write(buffer)
            buffer = b''
        if data:
            sys.stdout.buffer.write(data)
        else:
            break
    else:
        if data:
            buffer += data

logger.info("Finished delay_buffer.")
