#!/usr/bin/env python3

from piwall2.logger import Logger
import sys
from piwall2.multicasthelper import MulticastHelper

log_level = Logger.get_level()
if log_level is None or log_level <= Logger.DEBUG:
    # Prevent MulticastHelper.__send_video_stream_msg debug logs from being too spammy
    Logger.set_level(Logger.INFO)    

m = MulticastHelper()
while True:
    data = sys.stdin.buffer.read(4096)
    if not data:
        break
    i = 0
    while True:
        chunk = data[i:(i + 1472)]
        i += 1472
        if chunk:
            m.send(chunk, MulticastHelper.MSG_TYPE_VIDEO_STREAM)
        else:
            break
