#!/usr/bin/env python3

import argparse
import os
import traceback
from piwall2.videoreceiver import VideoReceiver
from piwall2.logger import Logger

def parseArgs():
    parser = argparse.ArgumentParser(description='piwall2 video broadcaster')
    parser.add_argument('--command', dest='command', action='store', required=True,
        help='command to run')
    parser.add_argument('--log-uuid', dest='log_uuid', action='store',
        help='Logger UUID')

    args = parser.parse_args()
    return args


args = parseArgs()
try:
    VideoReceiver().receive(args.command, args.log_uuid)
except Exception:
    logger = Logger().set_namespace(os.path.basename(__file__))
    logger.error(f'Caught exception: {traceback.format_exc()}')
