#!/usr/bin/env python3

import argparse
from piwall2.receiver import Receiver

def parseArgs():
    parser = argparse.ArgumentParser(description='piwall2 video broadcaster')
    parser.add_argument('--command', dest='command', action='store', required=True,
        help='command to run')

    args = parser.parse_args()
    return args


args = parseArgs()
Receiver().receive(args.command)
