#!/usr/bin/env python3

import argparse

from piwall2.broadcaster.videobroadcastthrottler import VideoBroadcastThrottler

def parseArgs():
    parser = argparse.ArgumentParser(description='piwall2 video sender')
    parser.add_argument('--size', dest='size', action='store', required=True, type=int,
        help='video size in bytes.')
    parser.add_argument('--duration', dest='duration', action='store', required=True, type=int,
        help='video duration in seconds.')
    parser.add_argument('--log-uuid', dest='log_uuid', action='store',
        help='Logger UUID')

    args = parser.parse_args()
    return args


args = parseArgs()
video_broadcast_throttler = VideoBroadcastThrottler(args.size, args.duration, args.log_uuid)
video_broadcast_throttler.throttle_video()
