#!/usr/bin/env python3

import argparse
import sys
import time

def parseArgs():
    parser = argparse.ArgumentParser(description='Applies a timeout that starts ticking only ' +
        'after the first byte has been received')
    parser.add_argument('--timeout', dest='timeout', action='store', type=int,
        help='Timeout in seconds')

    args = parser.parse_args()
    return args


args = parseArgs()

first_byte_reception_time = 0
while True:
    data = sys.stdin.buffer.read(4096)    
    if first_byte_reception_time == 0:
        first_byte_reception_time = time.time()
    data = sys.stdout.buffer.write(data) 
    if (time.time() - first_byte_reception_time) > args.timeout:
        break
