#!/usr/bin/env python3
import argparse
import csv
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from piwall2.config import Config
from piwall2.configloader import ConfigLoader
from piwall2.logger import Logger

def parseArgs():
    parser = argparse.ArgumentParser(
        description=('Set the youtube API key used by the front end. ' +
            'If called with no arguments, print the current youtube API key (if any).'),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('--file', dest='file', action='store',
        help='A csv file consisting of two columns: youtube_url and duration (HH:MM:SS, H:MM:SS, MM:SS, or M:SS)')
    parser.add_argument('--shuffle', dest='shuffle', action='store_true',
        help='If set, we will randomize the order in which the list of videos is added to the queue.')
    args = parser.parse_args()
    return args


args = parseArgs()
Config.load_config_if_not_loaded(should_set_log_level = False)
ConfigLoader(should_set_log_level = False) # load config, e.g. set log level.

with open(args.file) as video_csv:
    csv_reader = csv.reader(video_csv)
    for row in csv_reader:
        print(f'{row}')
