#!/usr/bin/env python3

import argparse
import subprocess
import os
import sys
import shlex

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)
from piwall2.configloader import ConfigLoader
from piwall2.parallelrunner import ParallelRunner
from piwall2.broadcaster import Broadcaster

def parse_args():
    parser = argparse.ArgumentParser(description=
f"""Apply the receivers config located in: {config_loader.get_receivers_config_path()}.
This script should be run on the broadcaster. This script does several things:
1) Sets up passwordless SSH from the broadcaster to each receiver
2) Sets up the control daemon on the broadcaster
3) Sets up the receiver daemon on each receiver
""",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--receiver-ssh-password', dest='receiver_ssh_password', action='store', required=True,
        help="SSH password for logging into the receiver raspberry pis. If you haven't changed this, it will be 'raspberry'.")
    args = parser.parse_args()
    return args

# generate the SSH key that the broadcaster will use for passwordless SSH
def generate_ssh_key(file):
    print(f"Generating ssh key: {file} ...")

    dirname = os.path.dirname(file)
    output = (subprocess
        .check_output(
            f"mkdir -p {shlex.quote(dirname)}",
            shell = True,
            executable = '/usr/bin/bash',
            stderr = subprocess.STDOUT
        )
    )

    # https://stackoverflow.com/a/43235320/627663
    output = (subprocess
        .check_output(
            f"ssh-keygen -q -t ed25519 -N '' -f {shlex.quote(file)} <<<y >/dev/null 2>&1",
            shell = True,
            executable = '/usr/bin/bash',
            stderr = subprocess.STDOUT
        )
    )

def authorize_ssh_key(file, password):
    print("Getting list of receivers from config...")
    receivers = ParallelRunner().quote_machines(ConfigLoader().get_receivers_list())
    authorize_ssh_key_cmd = (
        f"sshpass -p {shlex.quote(password)} " +
        "ssh-copy-id " +
        "-o ConnectTimeout=5 " +
        "-o UserKnownHostsFile=/dev/null " +
        "-o StrictHostKeyChecking=no " +
        "-o LogLevel=ERROR " +
        f"-i {shlex.quote(file)} " + "pi@{}"
    )

    print(f"Authorizing ssh key on receivers: {receivers}")

    parallel_cmd = (
        "parallel --will-cite --max-procs 16 " +
        # exit when the first job fails. Kill running jobs.
        # If fail=1 is used, the exit status will be the exit status of the failing job.
        "--halt now,fail=1 " +
        f'"{authorize_ssh_key_cmd}" ::: {receivers}'
    )
    output = (subprocess
        .check_output(
            parallel_cmd,
            shell = True,
            executable = '/usr/bin/bash',
            stderr = subprocess.STDOUT
        )
    )


config_loader = ConfigLoader(load = False)
args = parse_args()

# load after parsing args to avoid potentially throwing errors before printing the help text
config_loader.load_config_if_not_loaded()
generate_ssh_key(Broadcaster.SSH_KEY_PATH)
authorize_ssh_key(Broadcaster.SSH_KEY_PATH, args.receiver_ssh_password)
print("Success!")
