#!/usr/bin/env python3
# This is called in the ./install/setup_broadcaster_and_receivers script
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from piwall2.cmdrunner import CmdRunner
from piwall2.config import Config
from piwall2.configloader import ConfigLoader

Config.load_config_if_not_loaded()

cmd_runner = CmdRunner()
ssh_opts = ' '.join(CmdRunner.STANDARD_SSH_OPTS)
scp_cmd = (
    f'scp {CmdRunner.SSH_KEY_PATH_FLAG} {ssh_opts} ' +
    f'{ConfigLoader.CONFIG_PATH} pi@{{}}:{ConfigLoader.CONFIG_PATH}'
)
cmd_runner.run_parallel(scp_cmd, include_broadcaster = False)
