#!/usr/bin/env python3

import argparse
import os
import shlex
import subprocess
import sys
import time
import urllib.request

# This is necessary for the imports below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)
from piwall2.broadcaster.videobroadcaster import VideoBroadcaster
from piwall2.configloader import ConfigLoader
from piwall2.logger import Logger

def parseArgs():
    parser = argparse.ArgumentParser(
        description=('download a video from youtube in the format ' +
            'required to make it a user defined loading screen video or a screensaver video. ' +
            'Videos may be cropped via: https://stackoverflow.com/a/42827058/627663 . ' +
            'Sound may be stripped via: https://superuser.com/a/268986/1417348 .'),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('--url', dest='url', action='store', required = True,
        help='youtube video url')
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--1080p', dest='video_quality', action='store_const', const='1080p', default='1080p')
    group.add_argument('--720p', dest='video_quality', action='store_const', const='720p', default='1080p')
    parser.add_argument('--output-file', dest='output_file', action='store', required = True,
        help='output file without file extension')
    parser.add_argument('--with-thumbnail', dest='with_thumbnail', action='store_true', default=False,
        help='Download thumbnail image as well')
    args = parser.parse_args()
    return args


logger = Logger()
args = parseArgs()
broadcaster = VideoBroadcaster(args.url, log_uuid = '', show_loading_screen = False)
if args.video_quality == '1080p':
    ytdl_video_format = ConfigLoader.SINGLE_VIDEO_OUTPUT_YTDL_VIDEO_FORMAT
elif args.video_quality == '720p':
    ytdl_video_format = ConfigLoader.DUAL_VIDEO_OUTPUT_YTDL_VIDEO_FORMAT
else:
    logger.error(f"Invalid video quality: {args.video_quality}")
    sys.exit(1)

download_and_convert_video_proc = broadcaster.start_download_and_convert_video_proc(ytdl_video_format = ytdl_video_format)
write_output_proc = subprocess.Popen(
    f'cat - >{shlex.quote(args.output_file + ".ts")}', shell = True, executable = '/usr/bin/bash',
    stdin = download_and_convert_video_proc.stdout
)

while write_output_proc.poll() is None:
    time.sleep(0.1)

if write_output_proc.returncode != 0:
    logger.error(f"Got non-zero exit code: {write_output_proc.returncode}")
    sys.exit(write_output_proc.returncode)

if args.with_thumbnail:
    video_id = (subprocess
        .check_output(
            (f'yt-dlp --retries infinite --print id {shlex.quote(args.url)}'),
            shell = True, executable = '/usr/bin/bash', stderr = subprocess.STDOUT)
        .decode("utf-8"))
    thumbnail_url = f'https://i.ytimg.com/vi/{video_id}/mqdefault.jpg'
    logger.info(f"Downloading thumbnail: {thumbnail_url}...")
    urllib.request.urlretrieve(thumbnail_url, f'{args.output_file}.jpg')
