#!/usr/bin/env python3
import argparse
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from piwall2.configloader import ConfigLoader
from piwall2.logger import Logger

def parse_args():
    parser = argparse.ArgumentParser(description=
f"""This is called in the install/install.sh script
This script should be run on a receiver. This script prints out the specified config values
for this receiver as it is set in the config file {ConfigLoader.CONFIG_PATH}.
""",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--keys', dest='keys', action='store', default='',
        help="Comma separated list of keys. We will print the corresponding values of these keys, or a " +
        "blank line if the key is not set.")
    args = parser.parse_args()
    return args

def main():
    Logger.set_level(Logger.QUIET) # silence any other output to stdout, because we parse this script's stdout output.
    if not os.path.isfile(ConfigLoader.CONFIG_PATH):
        print(f"Config file does not exist at path {ConfigLoader.CONFIG_PATH}.")
        sys.exit(0)

    args = parse_args()
    config_keys_to_print = args.keys.split(',')
    receiver_config_stanza = ConfigLoader().get_own_receiver_config_stanza()
    for key in config_keys_to_print:
        print(receiver_config_stanza.get(key, ''))


main()
