#!/usr/bin/env python3

import argparse
import subprocess
import os
import socket
import sys
import shlex
import time

# This is necessary for the piwall2 imports that come later to work
ROOT_DIR = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(ROOT_DIR)

# Keep this in-sync with ConfigLoader::RECEIVERS_CONFIG_PATH. We cannot reference that constant here
# because using the ConfigLoader class imports a bunch of modules that we may not have installed
# yet. This script is the thing that installs those modules.
RECEIVERS_CONFIG_PATH = ROOT_DIR + '/receivers.toml'

def main():
    args = parse_args()

    install_bootstrap_dependencies()

    # import must come after the bootstrap dependencies have been installed
    from piwall2.cmdrunner import CmdRunner

    cmd_runner = CmdRunner()
    if args.setup_ssh:
        if args.ssh_password is None:
            raise Exception("When setting up SSH, '--receiver-ssh-password' must be specified.")
        generate_ssh_key(CmdRunner.SSH_KEY_PATH)
        authorize_ssh_key(CmdRunner.SSH_KEY_PATH, args.ssh_password, cmd_runner, CmdRunner.STANDARD_SSH_OPTS)
    clone_and_pull_repo(cmd_runner, CmdRunner.STANDARD_SSH_OPTS)
    copy_config_to_receivers(cmd_runner)
    if args.install_dependencies:
        install_dependencies(cmd_runner)
    if args.install_app:
        install_app(cmd_runner, args.dont_disable_wifi)

    # The step install_app require a restart
    restart_hosts_if_necessary(cmd_runner, is_last_step = True)

def parse_args():

    parser = argparse.ArgumentParser(description=
f"""Applies the receivers config located in: {RECEIVERS_CONFIG_PATH}.
This script should be run on the broadcaster. This script does several things:
1) Sets up passwordless SSH from the broadcaster to each receiver
2) Installs piwall2 dependencies on the broadcaster and receivers
3) Installs the application on the broadcaster and receivers
""",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--dont-setup-ssh', dest='setup_ssh', action='store_false', default=True,
        help="Skip setting up SSH.")
    parser.add_argument('--ssh-password', dest='ssh_password', action='store', default=None,
        help="SSH password for logging into the broadcaster and receiver raspberry pis. If you " +
        "haven't changed this, it will be 'raspberry'. Required if setting up SSH.")
    parser.add_argument('--dont-install-dependencies', dest='install_dependencies', action='store_false',
        default=True, help="Skip installing dependencies.")
    parser.add_argument('--dont-install-app', dest='install_app', action='store_false',
        default=True, help="Skip installing app.")
    parser.add_argument('--dont-disable-wifi', dest='dont_disable_wifi', action='store_true', default=False,
        help="Don't disable wifi. Only specify this option if you know what you're doing.")
    args = parser.parse_args()
    return args

# generate the SSH key that the broadcaster will use for passwordless SSH
def generate_ssh_key(file):
    print(f"Generating ssh key: {file} ...")

    dirname = os.path.dirname(file)
    output = (subprocess
        .check_output(
            f"mkdir -p {shlex.quote(dirname)}",
            shell = True,
            executable = '/usr/bin/bash',
            stderr = subprocess.STDOUT
        )
    )

    # https://stackoverflow.com/a/43235320/627663
    output = (subprocess
        .check_output(
            f"ssh-keygen -q -t ed25519 -N '' -f {shlex.quote(file)} <<<y >/dev/null 2>&1",
            shell = True,
            executable = '/usr/bin/bash',
            stderr = subprocess.STDOUT
        )
    )

def authorize_ssh_key(file, password, cmd_runner, ssh_opts):
    print("Authorizing ssh key on broadcaster and receivers...")
    ssh_opts = ' '.join(ssh_opts)
    authorize_ssh_key_cmd = (
        f"sshpass -p {shlex.quote(password)} " +
        f"ssh-copy-id {ssh_opts} " +
        f"-i {shlex.quote(file)} " + "pi@{}"
    )
    cmd_runner.run_parallel(authorize_ssh_key_cmd)

def clone_and_pull_repo(cmd_runner, ssh_opts):
    git_url = (subprocess
        .check_output(
            f"git config --file {ROOT_DIR}/.git/config --get remote.origin.url",
            shell = True, executable = '/usr/bin/bash', stderr = subprocess.STDOUT
        )
    ).decode('utf-8').strip()

    # https://stackoverflow.com/a/12142066/627663
    current_branch = (subprocess
        .check_output(
            f"GIT_DIR={ROOT_DIR}/.git git rev-parse --abbrev-ref HEAD",
            shell = True, executable = '/usr/bin/bash', stderr = subprocess.STDOUT
        )
    ).decode('utf-8').strip()

    print(f"Cloning or pulling repo {git_url} into {ROOT_DIR} on receivers and checking out branch " +
        f"{current_branch}...")

    ssh_opts = 'ssh ' + ' '.join(ssh_opts) # Prevent 'Host key verification failed.' errors with ssh opts
    clone_or_pull_repo_and_checkout_branch = (
        f'if [ ! -d "{ROOT_DIR}" ]; then echo "Cloning repo..." && ' +
        f'GIT_SSH_COMMAND="{ssh_opts}" git clone "{git_url}" "{ROOT_DIR}"; '
        f'else echo "Pulling repo..." && GIT_SSH_COMMAND="{ssh_opts}" git -C "{ROOT_DIR}" pull; fi && ' +
        f'git -C {ROOT_DIR} checkout {current_branch} && '
        # pull a second time after checking out the right branch. AFAIK, pull only updates the branch you are
        # currently on?
        f'GIT_SSH_COMMAND="{ssh_opts}" git -C "{ROOT_DIR}" pull'
    )
    cmd_runner.run_dsh(clone_or_pull_repo_and_checkout_branch, include_broadcaster = False)

def copy_config_to_receivers(cmd_runner):
    print("Copying config (if it exists) from broadcaster to receivers...")
    cmd = ROOT_DIR + "/utils/copy_config_to_receivers"
    exit_code = cmd_runner.run_cmd_with_realtime_output(cmd, raise_on_failure = False)
    if exit_code == 99:
        # This indicates the config file could not be found. That's ok, let people be able to define it later
        # and finish the setup.
        pass
    elif exit_code != 0:
        raise Exception(f"Unable to run {cmd}!")

def install_dependencies(cmd_runner):
    broadcaster_and_receivers = cmd_runner.get_broadcaster_and_receivers_hostname_list()
    broadcaster_hostname = socket.gethostname()
    print(f"Installing dependencies on: {broadcaster_and_receivers}...")
    install_deps_cmd = (f"{ROOT_DIR}/install/install_dependencies.sh -t " +
        f"$(if [[ $(hostname) == \"{broadcaster_hostname}\" ]]; then echo broadcaster ; else echo receiver ; fi)")
    cmd_runner.run_dsh(install_deps_cmd)

def install_app(cmd_runner, dont_disable_wifi):
    broadcaster_and_receivers = cmd_runner.get_broadcaster_and_receivers_hostname_list()
    broadcaster_hostname = socket.gethostname()
    print(f"Installing app on: {broadcaster_and_receivers}...")
    install_app_cmd = (f"{ROOT_DIR}/install/install.sh -t " +
        f"$(if [[ $(hostname) == \"{broadcaster_hostname}\" ]]; then echo broadcaster ; else echo receiver ; fi)")
    if dont_disable_wifi:
        install_app_cmd += " -w"
    cmd_runner.run_dsh(install_app_cmd)

# install dependencies necessary to run this script
def install_bootstrap_dependencies():
    print("Determining which bootstrap apt dependencies to install...")

    # install dependencies from apt package manager
    deps = ['parallel', 'dsh', 'sshpass', 'python3-pip']
    deps_to_install = []
    for dep in deps:
        if not is_program_installed(dep):
            deps_to_install.append(dep)
    if deps_to_install:
        deps_to_install = ' '.join(deps_to_install)
        print(f"Installing bootstrap apt dependencies from: {deps_to_install}...")
        run_cmd_with_realtime_output(f"sudo apt -y install {deps_to_install}")
    else:
        print("No bootstrap apt dependencies needed installing.")

    print("Installing bootstrap python dependencies...")
    run_cmd_with_realtime_output(ROOT_DIR + '/install/install_dependencies.sh -p -t broadcaster')

def is_program_installed(program):
    try:
        output = (subprocess
            .check_output(
                f"which {shlex.quote(program)}",
                shell = True,
                executable = '/usr/bin/bash',
                stderr = subprocess.STDOUT
            )
        )
    except subprocess.CalledProcessError as e:
        if e.returncode == 1:
            return False
        else:
            raise e
    except Exception as e:
        raise e
    return True

# Reimplimentation of CmdRunner::run_cmd_with_realtime_output. We need to run this method with no
# dependencies in this setup script, because this script is the thing that installs those dependencies.
def run_cmd_with_realtime_output(cmd, raise_on_failure = True):
    print(f"Running command: {cmd}")
    proc = subprocess.Popen(
        cmd, shell = True, executable = '/usr/bin/bash'
    )
    while proc.poll() is None:
        time.sleep(0.1)
    if proc.returncode != 0 and raise_on_failure:
        raise Exception(f"The process for cmd: [{cmd}] exited non-zero: " +
            f"{proc.returncode}.")
    return proc.returncode

# The install scripts will create a special file in /tmp if a restart is required after they run.
# After the install scripts run, we let this coordinator script determine if a restart is required to avoid
# restarting the broadcaster while it is still in the middle of running a dsh command

# The raspberry pi appears to delete the whole /tmp directory upon restart, so we don't need to do anything
# special to delete the file once we've restarted.
def restart_hosts_if_necessary(cmd_runner, is_last_step = False):
    print("Restarting hosts if necessary...")

    # restart receivers, if necessary
    cmd = ('{ [ -f /tmp/piwall2_install_restart_required ] && echo "Restarting..." && ' +
        'sudo shutdown -r now ; } || echo "Restart not needed."')
    exit_status = cmd_runner.run_dsh(cmd, include_broadcaster = False, raise_on_failure = False)
    if exit_status == 255 or exit_status == 0:
        pass # Exit code 255 is expected if a host restarts: `Connection to <hostname> closed by remote host.`
    else:
        raise Exception(f"The process for cmd: [{cmd}] exited non-zero: {exit_status}.")

    if is_last_step:
        print("Setup completed successfully! The last step is a restart which may or may not be required...")

    # restart broadcaster, if necessary
    cmd_runner.run_cmd_with_realtime_output(cmd.strip("'"))


main()
