# Controlling video broadcast speed
:toc:
:toclevels: 5

## ffmpeg -re
Ffmpeg provides a flag `-re`:
....
-re (input)
   Read input at native frame rate. Mainly used to simulate a grab device, or live input stream (e.g. when reading from a file). Should not be used with actual grab devices or live input
   streams (where it can cause packet loss).  By default ffmpeg attempts to read the input(s) as fast as possible.  This option will slow down the reading of the input(s) to the native frame
   rate of the input(s). It is useful for real-time output (e.g. live streaming).
....

In other words, the `-re` flag transmits the video at "1x" speed. Without this flag, ffmpeg will transmit the video as fast as possible, which may be at about 50x speed in some cases. Transmitting the video too fast will exhaust various input buffers on the receivers. As the video is transmitted via multicast, shell pipeline backpressure cannot be leveraged to automatically throttle the video broadcast. By using the `-re` flag, we could easily ensure the video is transmitted at a rate that will not overwhelm input buffers on the receivers. To be pedantic though, to the extent that there is clock drift between the broadcaster and receiver, even using ffmpeg's `-re` flag might not be sufficient to avoid overwhelming receiver buffers. If the broadcaster's clock is slightly fast, then the broadcaster will send video slightly faster than the receiver can process it. After a long period of time (perhaps days), the receiver's input buffers may be overwhelmed. Likewise, if the receiver's clock is slightly fast, then the broadcaster will send video slightly slower than the receiver can process it. The receiver's buffers might eventually get drained, causing playback issues. See https://github.com/popcornmix/omxplayer/issues/482#issuecomment-253218683[this comment] for more details.

But, `-re` generally works well enough for us as we are not usually playing ridiculously long videos. Thus, we might attempt something like this:
....
ffmpeg -re  -i <input> -c:v copy -c:a mp2 -b:a 192k -f mpegts "udp://239.0.1.23:1234"
....

This works pretty well, but there is a problem: dbus.

### dbus
We use dbus to control omxplayer on the receivers. Omxplayer provides a https://github.com/popcornmix/omxplayer/#dbus-control[dbus interface] to control many aspects of the player: volume, crop positions, etc. We noticed that sending dbus messages to omxplayer could be quite slow. In some cases it would be fast (~30 ms), but in other cases, it could be quite slow (over 1 sec). See https://docs.google.com/spreadsheets/d/1jB3cf7_d_jQxHmjWCLvt7DCgGCIJfhZ2V6EG4J1_AsA/edit#gid=0[timings we collected here].

This was no good -- our dbus messages would have a ridiculous lag trying to control omxplayer. We https://github.com/dasl-/omxplayer/commit/65e1b16fb9c2eafcbfd6021ed7b0ffa272d45afd[added timing logs to omxplayer] to get more insight. Through additional timing logs, as well as profiling via strace, we determined that omxplayer would occasionally block for a while on `read` syscalls, sometimes for over one second. I don't know exactly where in omxplayer's code this blocking read happens, but I suspect it's https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/OMXReader.cpp#L512[here or somewhere else in the OMXReader::Read method]. This could be definitively determined by adding more timing logs.

It turns out these blocking reads were the cause of the dbus message slowness. Omxplayer has a https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/omxplayer.cpp#L1185[main loop] where it basically does (pseudocode):

....
while True:
    if (time since last dbus message check is over 20 ms ago):
        check_for_new_dbus_messages()
    read_next_video_bytes_from_stdin_and_send_to_gpu()
....

See https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/omxplayer.cpp#L1199-L1201[here] for where omxplayer checks for dbus messages.

As is evident from the pseudocode, if a read blocks for over one second, there is no way we can check for dbus messages within one second as the main loop is busy reading the video bytes. So why were the reads taking so long? I tried reducing the read buffer from https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/OMXReader.h#L47[the default], which was a large value (32768). I https://github.com/dasl-/omxplayer/commit/bf18fe6aaaa0b012252b33e142f8e4c3fa42719f[reduced them] to as small as 1024 IIRC, which was as small as they would go as evidenced from tracing the read calls via `strace`. This reduced the read duration a little bit, but it was not nearly enough.

I noticed that in the abscence of ffmpeg's `-re` flag, omxplayer's reads happened much more quickly. Presumably this is because with ffmpeg's `-re` flag, omxplayer has to wait for all the bytes it wants to read to be streamed. This suggests that if we could send data faster, omxplayer's reads might not block for as long.

Other things that we might consider for reducing omxplayer's read syscall duration include somehow setting timeouts around omxplayer's reads. Omxplayer has some ability to set timeouts (see https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/OMXReader.cpp#L53[here] and https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/OMXReader.cpp#L98[here]), but I'm not sure how it works exactly. Or perhaps we could somehow check ahead of time how many bytes are available for reading, and if not enough bytes are available, we could skip the read until the next loop. I did not investigate these approaches, instead opting to find a way to remove ffmpeg's `-re` flag to speed up omxplayer's reads.

## Removing ffmpeg's -re flag with "initial burst" via shell pipeline backpressure
Obviously if we simply remove ffmpeg's `-re` flag, we risk sending the video too quickly, overflowing various receiver input buffers. This is more of a risk on long videos, as shorter videos are more likely to be able to fit into receiver input buffers without overflowing. The solution we came up with is to send the first several megabytes of the video in a burst (as fast as possible), whereas the remaining bytes will be sent at 1x speed. Here's how the video burst can be implemented (formatted for easier reading, but the whitespace may not be valid for copy / pasting on the command line):
....
ffmpeg -i <input> -c:v copy -c:a mp2 -b:a 192k -f mpegts - |
    tee
        >(mbuffer -q -l /tmp/mbuffer.out -m 209715200b |
            ffmpeg -re -i pipe:0 -c:v copy -c:a copy -f mpegts - >/dev/null)
        >(ffmpeg -i pipe:0 -c:v copy -c:a copy -f mpegts "udp://239.0.1.23:1234")
        >/dev/null
....

The first ffmpeg command here does not have the `-re` flag, thus it will attempt to send as fast as possible. In the tee, we are first teeing to mbuffer piped to ffmpeg. This second ffmpeg does have the `-re` flag, thus it will process the video at 1x speed. Thus, this first tee output will apply pipeline backpressure on the first ffmpeg command. But because this second ffmpeg is preceded by an mbuffer pipe with a buffer of 200 MB, the first 200 MB can be sent quickly before pipeline backpressure kicks in. We have an initial burst of 200 MB.

The second tee output is responsible for actually sending the video over UDP. Note that the second tee has a third ffmpeg command, this time without the `-re` flag. Thus, the second tee output will send the video as fast as possible. But because the first tee output is applying backpressure on the pipeline, the second tee will receive input data at 1x speed after the first 200 MB has been sent. This allows omxplayer to finish its reads quickly, because there is always about 200 MB of data available for it to read. It never has to wait for ffmpeg to broadcast more data before being able to read it.

With this approach, we just need to make sure the various receiver input buffers are large enough to contain the 200 MB initial burst that is sent. This is done by creating an appropriately sized mbuffer on the receiver side.

### Working out the kinks
We noticed that in the second tee output, the ffmpeg command that is actually responsible for broadcasting the video sometimes failed to send all the video bytes. We noticed this mainly when testing on a https://www.youtube.com/watch?v=zmr2I8caF0c[very short video]. This would result in the video sometimes failing to play, or cutting off the end of the video. These errors would happen perhaps one third of the time we attempted to play the video. After debugging, we suspected that ffmpeg may be failing to perform the UDP broadcast of all the data that it was being sent. Perhaps a similar issue to https://github.com/dasl-/piwall2/blob/60aa21ea7c0385673ee5206487eae7046d89d2eb/piwall2/broadcaster/videobroadcaster.py#L326-L335[what we described here with slow ffmpeg start-up times], or perhaps similar to what https://github.com/dasl-/piwall2/blob/main/docs/best_video_container_format_for_streaming.adoc#multicast-output-bug[we described here with buggy ffmpeg UDP broadcasting].

By implementing https://github.com/dasl-/piwall2/blob/60aa21ea7c0385673ee5206487eae7046d89d2eb/msend_video[our own video broadcaster], we removed the second tee output's reliance on ffmpeg and have a suitable workaround for the bug:
....
ffmpeg -i <input> -c:v copy -c:a mp2 -b:a 192k -f mpegts - |
    tee
        >(mbuffer -q -l /tmp/mbuffer.out -m 209715200b |
            ffmpeg -re -i pipe:0 -c:v copy -c:a copy -f mpegts - >/dev/null)
        >(./msend_video)
        >/dev/null
....

After implementing this workaround, we no longer saw issues.

### The results
By implementing this "initial burst", we drastically reduced dbus message sending latency. Sending dbus messages now takes 20-70ms. Furthermore, this allowed us to https://github.com/dasl-/piwall2/commit/33191fbfba5f9d4fe7725847b942eaa273cb9401[reduce omxplayer's threshold option from 5 to 0.2 seconds] (https://github.com/popcornmix/omxplayer/blob/1f1d0ccd65d3a1caa86dc79d2863a8f067c8e3f8/omxplayer.cpp#L1177[0.2 is the default]). Perhaps the reason we needed such a high threshold before was because omxplayer's reads would sometimes block for longer than omxplayer's input buffer length. With a threshold of 5 seconds, if a read took greater than 5 seconds to finish, we'd have exhausted our input buffer, causing a drop out. It would be interesting to profile omxplayer to determine if long reads were the reason we needed such a long threshold before.

With all these changes, we do occasionally see video synchronization bugs across the receivers. While I was testing with a setup consisting of 4 receivers, I noticed that approximately one out of thirty trials playing my https://www.youtube.com/watch?v=6wVZK0W0SAo[test video], the video playback would be slightly out of sync across all the receivers (perhaps half a second of synchronization differentials). This was most readily noticeable by listening to the audio.

I am not sure if the changes described in this document made these video synchronization bugs any worse than they used to be. They are so rarely occuring, that I might not have noticed them very much prior to making these changes. Perhaps it's only now that I stress tested everything with 30+ trials that I came across the issues. It would be interesting to revert to using ffmpeg's `-re` flag and the 5 second omxplayer threshold etc to see if the synchronization issues are any better in that setup. But they are so rarely occuring that it may be hard to get numbers significant enough to prove things one way or another.
