# Issues we've seen before
:toc:
:toclevels: 5

## Slow wifi 1
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=302370

## Slow wifi 2
If you are:

1. using an older version of the raspberry pi 4 and
1. using 2.4 ghz wifi and
1. using hdmi output at a resolution of 2,560 x 1,440 or above

then it could be https://www.zdnet.com/article/raspberry-pi-4-wi-fi-problem-firmware-update-will-fix-your-screen-resolution-bug/

## UDP packet loss
### Symptoms
* video pauses / freezes (either momentarily or permanently) on one or more TVs
* video glitches / artifacts on one or more monitors
* video never starts on one or more monitors
* video gets out of sync with respect to other TVs

### Diagnosing
#### Receive buffer filling up
The following command repeatedly watches for UDP receiver related errors. Run this on the receiver(s) which is experiencing issues while you are broadcasting a video.
....
% while sleep 1; do netstat -anus | grep receive | grep errors; done
    0 packet receive errors
    0 receive buffer errors
    0 packet receive errors
    0 receive buffer errors
    0 packet receive errors
    0 receive buffer errors
....

The number displayed is the number of errors since the pi was last rebooted. If the numbers are staying constant, then you are not currently getting any errors. If the numbers are increasing, you are currently getting UDP packet loss.

Many times, both of these numbers will have the same value. That is, the number of packet receive errors will be equal to the number of receive buffer errors. This may indicate a socket receive buffer is too small.

The following command shows default udp buffer sizes on a fresh install of raspbian:
....
% sudo sysctl -A | grep net | grep 'mem\|backlog' | grep 'udp_mem\|rmem_\|max_backlog'
net.core.netdev_max_backlog = 1000
net.core.rmem_default = 180224
net.core.rmem_max = 180224
net.ipv4.udp_mem = 15735    20983   31470
net.ipv4.udp_rmem_min = 4096
....

To print a display a socket's receive buffer size, you may do this in python:
....
>>> import socket
>>> import struct
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
>>> sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
>>> sock.bind(('239.0.1.23', 1234))
>>> mreq = struct.pack("4sl", socket.inet_aton('239.0.1.23'), socket.INADDR_ANY)
>>> sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
>>> print(sock.getsockopt(socket.SOL_SOCKET,socket.SO_RCVBUF))
180224
....

Observe how by default, a socket gets a receive buffer equal to `net.core.rmem_default`. Socket buffers may be changed via:
....
>>> sock.setsockopt(socket.SOL_SOCKET,socket.SO_RCVBUF, 99999)
>>> print(sock.getsockopt(socket.SOL_SOCKET,socket.SO_RCVBUF))
199998
....

Observe how a receive buffer was created that is double the size of what we specified. According to the man page:
....
       SO_RCVBUF
              Sets or gets the maximum socket receive buffer in bytes.
              The kernel doubles this value (to allow space for
              bookkeeping overhead) when it is set using setsockopt(2),
              and this doubled value is returned by getsockopt(2).  The
              default value is set by the
              /proc/sys/net/core/rmem_default file, and the maximum
              allowed value is set by the /proc/sys/net/core/rmem_max
              file.  The minimum (doubled) value for this option is 256.
....

This seemingly allows us to create sockets with receive buffers up to double the size specified in `net.core.rmem_max`:
....
>>> sock.setsockopt(socket.SOL_SOCKET,socket.SO_RCVBUF, 99999999)
>>> print(sock.getsockopt(socket.SOL_SOCKET,socket.SO_RCVBUF))
360448
....

This command lets us see the number of bytes that have not been read yet from the socket's receive buffer (`Recv-Q`):
....
% netstat -c --udp -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 0.0.0.0:5353            0.0.0.0:*
udp        0      0 0.0.0.0:51772           0.0.0.0:*
udp        0      0 0.0.0.0:68              0.0.0.0:*
udp        0      0 239.0.1.23:1234         0.0.0.0:*
udp6       0      0 :::5353                 :::*
udp6       0      0 :::39588                :::*
....

While a video is being broadcast, you may see the number for the Recv-Q number sometimes go above zero. If the Recv-Q value gets close to the socket's receive buffer size, you may start to see UDP packet loss. You can run both of these commands at the same time on the receiver to confirm:

....
% netstat -c --udp -an | grep '239.0.1.23:1234'
...
% # in a separate shell:
% while sleep 1; do netstat -anus | grep receive | grep errors; done
....

If the socket's receiver buffer is filling up, we'd expect to see the number of errors reported by the second command to start increasing at the same time that the socket's Recv-Q fills up according to the first command.

I am not sure if there are other reasons, aside from the receive buffer overflowing, for the "receive buffer errors" counter to be incremented.

#### Receive buffer too big
While debugging packet loss problems, I tried setting the socket's receive buffer to 64MB by changing the sysctl defaults:
....
net.core.rmem_default = 67108864
net.core.rmem_max = 67108864
....

Strangely, this sometimes caused problems of its own. While broadcasting a video, I'd sometimes see the symptoms of packet loss still (video glitches, pauses, etc). I'd see packet receive errors increasing while receive buffer errors stayed constant. They were not increasing in lockstep like before:
....
% while sleep 1; do netstat -anus | grep receive | grep errors; done
...
....

https://linux-tips.com/t/udp-packet-drops-and-packet-receive-error-difference/237/2[This post] pointed to a possible solution: decrease the socket buffer size. After making adjustments, everything seemed fine:
....
net.core.rmem_default = 4194304
net.core.rmem_max = 67108864
....

I am not sure what was wrong with using 64MB. This would be the default for all sockets on the system, so perhaps this created memory pressure? Or perhaps something else was going on. If 4MB is too small for some use cases, this may be worth investigating again.

## Receivers sometimes fail to play video
Receiver logs may look like this: https://gist.github.com/dasl-/f7b8326cf4735103b37f0cfa0ae4fb3f

Broadcaster logs may look like this: https://gist.github.com/dasl-/8247ccaf4953442fe2132e8792bf8d64

And omxplayer.log may look like this (note `ERROR: COMXPlayer::interrupt_cb - Timed out`): https://gist.github.com/dasl-/50037e84b837e3c6543fdc1839405b82

I believe the cause is that sometimes youtube-dl is slow to start the download, causing https://github.com/popcornmix/omxplayer/issues/426#issuecomment-182092009[omxplayer's timeout] to be exhausted. At the time of the issue described in these logs, we were using `--timeout 20` with omxplayer. I will try increasing to `--timeout 30`.

See also: https://github.com/dasl-/piwall2/blob/main/docs/configuring_omxplayer.adoc#timeout

For reference, I was testing with https://www.youtube.com/watch?v=rSLQ\--jza5U[this video]. Maybe one out of every five attempts it would take ~20 - 22 seconds to start the youtube-dl download.

## The setup_broadcaster_and_receivers script fails

### Failure due to raspbian package repositories being down
You may see errors earlier in the script output like:
....
pi@piwall6.local: Err:115 http://raspbian.raspberrypi.org/raspbian buster/main armhf libtevent0 armhf 0.9.37-1
pi@piwall6.local:   Cannot initiate the connection to raspbian.raspberrypi.org:80 (2a00:1098:0:80:1000:75:0:3). - connect (101: Network is unreachable) Could not connect to raspbian.raspberrypi.org:80 (93.93.128.193), connection timed out [IP: 93.93.128.193 80]
....
This is likely a transient failure for the raspbian package servers. Try again.

## Video playback freezes: cause 1
Playback will freeze on a single TV, while the other TVs in the TV wall continue playback normally. Not totally sure what's going on here yet. I notice freezing is more common when playing the https://www.youtube.com/watch?v=-pdVUsCqd2U[dvd bounce screensaver]. Sometimes restarting the receiver service fixes things (only for playback to freeze again later), but sometimes not. Restarting always fixes the problem, only for it to recur later. Sometimes I am able to reliably reproduce the problem with every play of the DVD bounce video.

The problem appears specific to a given TV or raspberry pi -- generally two of my TVs have this problem, one more often than the other. I have tried swapping the hardware out to determine if it's the hardware. This gave conflicting results. In one test, I swapped a plugged a "defective" pi into a different TV (keeping the SD card, but using different cables). The problem recurred, seeming to isolate the problem to the pi hardware or the SD card. But in another round of testing, I replaced "good" pis with the "defective" pi, using the "good" pi's SD card inserted into the bad pi. I noticed no playback freezing, indicating that the pi hardware itself was not the cause of the freezing. That leaves the SD card. I plugged the "defective" SD card into a good pi, and that resulted in no freezing. So I'm not sure wtf is going on.

Perhaps interference of some sort is at play? Maybe getting cases for the pis would help -- sometimes parts of the electrified metal chasis make contact with neighboring pis, resulting in shorts.

When this freeze happens, you may see nothing in the omxplayer logs. Although on the video _after_ the freeze started (if the issue does not magically fix itself on the subsequent playback as it sometimes does), you may see in the omxplayer logs (https://gist.github.com/dasl-/27adea01ef45ab406597cf4312363e7b[full logs]):

....
ERROR: COMXVideo::Open error OMX_IndexConfigDisplayRegion omx_err(0x80001001)
...
ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.video_decode - OMX_ErrorStreamCorrupt, Bitstream corrupt
....

Note that the `OMX_IndexConfigDisplayRegion` errors always appear to happen after dbus crop messages. Not sure what to make of this. Using `strace` doesn't give much insight. You may notice output like this from stracing omxplayer:
....
ioctl(4</dev/vchiq>, _IOC(_IOC_WRITE, 0xc4, 0x4, 0xc), 0xbedceabc) = 0
futex(0x3a6804, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
....

But this is actual normal strace output for a functioning omxplayer instance.

In a final note about this issue, after swapping the "defective" raspberry pi around to a bunch of TVs, I finally restored it to its original TV location (i.e. original defective pi, simcard, and cables). Previously to moving it around, I had been able to reproduce the freezing issue with virtually every playback of the dvd bounce issues. But after returning it here, I was unable to reproduce the issue at all after two full playthroughs of the dvd bounce video. So maybe this does mean it's related to physical positioning of the pi, interference, electrical contact, etc?

UPDATE: this has mostly been solved by rate limiting how fast we send: https://github.com/dasl-/piwall2/commit/b7e3a21efc9b3a493b254160bf0b108ab69f1345 The problem still happens sometimes, but it seems to happen less often.

Some more notes on the issue:

* if i get rid of the dbus commands that set volume and crop mode, i cannot reproduce the bug: https://gist.github.com/dasl-/af2962657bd22d35c6c176d4f8befdcd
** getting rid of only one of the volume or crop mode dbus commands does not prevent the bug. both must be removed
* I am semi-sure that reproducing this bug requires that we are sending dbus commands before / while the video is starting up.
** If the above diff is applied, the bug can be reproduced by sending dbus commands in a loop: https://gist.githubusercontent.com/dasl-/9aa90e723967d3008b97a7c4c0a3e4f8/raw/79d00a963a2ecb23af295ea49bd9210317e3301d/gistfile1.txt
** But the loop must be started BEFORE the video starts to play
** A list of dbus commands that can be useful for playing around: https://gist.githubusercontent.com/dasl-/e0a5b3297bd360025151f53d84322a6d/raw/02cb912331c956431ac3aaf2ce3486d46f3e2461/gistfile1.txt
* if stracing the omxplayer process, the bug does not seem occur: `sudo strace -p $(pidof omxplayer.bin) -y -Ttt`
** wtf no idea what this means...? https://unix.stackexchange.com/questions/148333/can-strace-ptrace-cause-a-program-to-crash
** once, while stracing the omxplayer process, I stopped stracing. Immediately after strace detached from the process, the video hung!
* once the bug starts to occur, it commonly recurs, but it might take a while to get the first occurence of the bug
* omxplayer logs via `--genlog` don't have any useful info
* attaching to omxplayer with strace AFTER it has frozen is not helpful -- it shows normal execution syscalls as if nothing is frozen.
* nothing in `dmesg`, the pi is not overheating nor undervoltage.
** `vcgencmd get_throttled` returns that everything is fine: `throttled=0x0`
* this bug used to happen a lot on piwall7. I replaced the hardware (just the pi itself) and now it's not happening
* this bug has been observed to happen VERY rarely on piwall9. Last observed on 2022-01-15. Have not replaced this hardware yet.
* this bug has been observed to happen VERY rarely on piwall3. Observed on 2022-02-12 and 2022-02-22. Have not replaced this hardware yet.
* This github issue appears to be the same bug? I made a post in the thread: https://github.com/Hexxeh/rpi-firmware/issues/249

## Video playback freezes and ssh becomes slow
In this failure mode, not only does video playback freeze, but if you try to ssh onto any / all of the pis, it will take a while to complete the ssh connection. In debugging this issue, I noticed that via `dsh`, I could eventually ssh onto all of the pis (albeit slowly, might take ~5 minutes) except for one! I decided to touch the raspberry pis to feel how hot they were. I noticed that the one pi that I could not ssh onto was very hot -- it would hurt to touch the CPU on it. Whereas the other raspberry pis were not nearly as hot as the one that I could not ssh onto. Unplugging the ethernet cable from this one "bad apple" pi immediately resolved the slow ssh / video playback problem. In my case, the "bad apple" pi was piwall2.local. Restarting the pi (by unplugging the power cable) seemed to fix everything. I seem to recall that this issue has happened once before with the same "bad apple" pi, but I cannot remember 100% if it was the same one (piwall2). If it was the same one, this seems to be a very rarely occuring bug that affects the same pi... hm... I would like to wait and see if the issue recurrs with the same pi.
