# Issues cropping videos for streaming playback
:toc:
:toclevels: 5

## Background
We will have an array of TVs in the video wall, potentially 9 (3x3) or 16 (4x4) TVs. We want to stream youtube videos to playback onto them. Each TV will display a fraction of the full video (one ninth or one sixteenth). There will be one "broadcaster" and N (9 or 16) "receiver" raspberry pis. Each receiver is responsible for displaying the video on its corresponding TV.

## Cropping videos with VLC
Each receiver raspberry pi will receive the full video sent by the broadcaster raspberry pi. The receiver is responsible for cropping the video such that it displays only a fraction (one ninth or one sixteenth) of the full video.

VLC has the ability to crop videos: https://wiki.videolan.org/VLC_HowTo/Crop/

But these cropping options seem to fail on the raspberry pi (https://gist.github.com/dasl-/c7f317a9fa47100d4c627fbf70838e46[full output]):
....
% cvlc today.mp4 "--video-filter=croppadd{cropleft=100}"
ERRORS...
....
The audio will play, but no video is displayed.

Googling the errors, we find a https://forum.videolan.org/viewtopic.php?t=149455[solution from a VLC developer]. And some more https://github.com/RPi-Distro/vlc/issues/2#issuecomment-535591883[info from raspberry pi employees on github].

### Solution
The full solution:
....
% cvlc today.mp4 "--video-filter=croppadd{cropleft=300}" --codec avcodec,none
....

Info about the `--codec` flag:
....
 Decoders
 This option can be used to alter the way VLC selects its codecs (decompression methods). Only advanced users should alter this option as it can break playback of all your streams.
      --codec <string>           Preferred decoders list
          List of codecs that VLC will use in priority. For instance, “dummy,a52” will try the dummy and a52 codecs before trying the other ones. Only advanced users should alter this option as it can
          break playback of all your streams.
....

Using `--codec avcodec,none` means we will be using software video decoding rather than hardware video decoding. Thus, CPU usage is much higher. In one test I performed, I found that `cvlc today.mp4` used ~8% CPU whereas `cvlc today.mp4 --codec avcodec,none` used ~20% CPU. This was on a video with 640x360 resolution. The higher the video resolution, the higher the CPU usage will be, especially when using software video decode. Although we will not be able to use hardware video decoding, at least it works!
