# TV output options
:toc:
:toclevels: 5

## HDMI video output options
### One vs two TVs per receiver raspberry pi
The raspberry pi 4 has two hdmi outputs. Thus, we could conceivably connect up to two TVs per receiver raspberry pi. There are pros and cons of connecting one vs two TVs per raspberry pi.

Using two TVs per raspberry pi allows you purchase fewer raspberry pis to control your TVs.

Using two TVs per raspberry pi means we will only be able to work with link:video_formats_and_hardware_acceleration.adoc#video-resolution[720p video at best] when playing two videos, whereas with one TV per raspberry pi, we can work with up to 1080p video.

### HDMI config options
If your HDMI display's resolution was not automatically detected (I use a https://amzn.to/3wWHE7T[HDMI to RCA converter] to power CRT TVs -- the resolution of my TVs was not automatically properly detected, perhaps because of the use of this converter), you may need to edit `/boot/config.txt`.

In my case, I had to add stanzas for `hdmi_group` and `hdmi_mode` (https://www.raspberrypi.org/documentation/configuration/config-txt/video.md[docs]):
....
hdmi_group:0=1
hdmi_group:1=1
hdmi_mode:0=1
hdmi_mode:1=1
....
After doing this, the TVs displayed the correct resolution. Whether you need to add these stanzas and if so, what their values should be, may vary depending on what sort of TVs you are using and if you have any HDMI to RCA converters in your signal path. See these https://www.raspberrypi.org/documentation/configuration/hdmi-config.md[raspberry pi docs for more info about what hdmi modes your device supports].

## Composite video output options
The raspberry pi also supports link:img/composite_video.jpg[composite video] (a.k.a "RCA video") via a https://www.adafruit.com/product/2881[cable like this]. As the raspberry pi only has one composite output, this option only allows you to control one TV per raspberry pi. If you are creating a CRT TV wall, I'd recommend using the composite output rather than using the HDMI output(s) combined with HDMI to composite converters. You don't actually end up saving very much money by using the two HDMI outputs to control two CRT TVs per raspberry pi after you account for the price of the https://amzn.to/3wWHE7T[HDMI to RCA converter], https://amzn.to/3gyUaoj[micro HDMI cables], and extra https://amzn.to/3tNCVmJ[USB power bank] that you will likely want to power all of the HDMI to RCA converters. Additional raspberry pi's are pretty cheap, and as mentioned above, using one TV per raspberry pi allows you to work with higher quality 1080p video.

To enable composite video output on a raspberry pi 4B, be sure to add `enable_tvout=1` to your `/boot/config.txt`. Note: the https://www.raspberrypi.org/documentation/configuration/config-txt/video.md[docs] say that enabling composite video output "slightly slows down the entire system".

There are a couple of additional composite https://www.raspberrypi.org/documentation/configuration/config-txt/video.md[video output options] you may want to adjust.

1. If you're not using NTSC TVs, you'll want to adjust `sdtv_mode` (most North American TVs use NTSC)
1. If you have a CRT with a non-standard aspect ratio, you'll want to adjust `sdtv_aspect`

## General video options
These video options apply to both HDMI and composite video output.

When displaying video, you may notice https://www.raspberrypi.org/documentation/configuration/raspi-config.md#underscan[overscan / underscan] issues. Overscan settings may be adjusted via the `overscan_{left,right,top,bottom}` options in `/boot/config.txt`. Note that these settings do not appear to apply to video players like omxplayer or vlc https://github.com/huceke/omxplayer/issues/103[unless you also set `overscan_scale=1`]. But enabling `overscan_scale` comes with a warning: "it can reduce image quality". Indeed, we see increased screen flicker when enabling `overscan_scale`. Thus it is debatable whether it is worth it to enable -- you trade a misaligned picture for a flickering picture.

In anecdotal testing, I have found that when using CRT TVs, I have slightly better aligned pictures when using the raspberry pi's HDMI output via an HDMI to RCA converter than when using the raspberry pi's composite video output.

For more on video calibration, see link:tv_calibration.adoc[the tv calibration docs].

## Video players
The below demonstrations use the following test videos (also https://www.youtube.com/watch?v=ucZl6vQ_8Uo[available on youtube]):
....
% youtube-dl https://www.youtube.com/watch\?v\=ucZl6vQ_8Uo -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio' --merge-output-format mkv -o sync_test_1080p.mkv
% youtube-dl https://www.youtube.com/watch\?v\=ucZl6vQ_8Uo -f 'bestvideo[vcodec^=avc1][height=720]+bestaudio' --merge-output-format mkv -o sync_test_720p.mkv
....
The conversion from mp4 to mkv container format is necessary because mp4 apparently isn't the best streaming container format (necessary when playing videos through pipes):
....
[mp4 @ 0xd6c0a0] muxer does not support non seekable output
....

### https://github.com/popcornmix/omxplayer/[omxplayer]
Due to our cropping needs, link:cropping_videos_for_streaming_playback.adoc[omxplayer is the preferred software to use for videoplayback in this project].

omxplayer may be installed via:
....
% sudo apt -y install omxplayer
....

#### One TV per raspberry pi

##### HDMI video output
This will play video with sound through the raspberry pi's first hdmi output.
....
% omxplayer -o hdmi sync_test_1080p.mkv
....

##### Composite video output
....
% omxplayer -o local sync_test_1080p.mkv
....

Note: comparing composite output to HDMI output through the HDMI to RCA converter, the composite output images are bigger because the composite output image overlaps the edges of the screen due to overscan.

#### Two TVs per raspberry pi

##### With ALSA sound
The latest version of omxplayer https://www.raspberrypi.org/forums/viewtopic.php?t=258647#p1578284[does not natively support outputting audio through the raspberry pi 4's second hdmi output]. As an alternative, we can rely on https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture[ALSA] to route the audio via omxplayer's `-o` option. Furthermore, we must now specify which hdmi port each omxplayer process will output through via omxplayer's `--display` option.

First, let's determine the ALSA device identifiers to use:
....
% aplay -L
...
default:CARD=b1
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Default Audio Device
...
default:CARD=b2
    bcm2835 HDMI 2, bcm2835 HDMI 2
    Default Audio Device
...
....

Next, let's determine the display numbers to use:
....
% tvservice -l
2 attached device(s), display ID's are :
Display Number 2, type HDMI 0
Display Number 7, type HDMI 1
....
These shouldn't change, because https://github.com/raspberrypi/userland/blob/3fd8527eefd8790b4e8393458efc5f94eb21a615/interface/vmcs_host/vc_dispmanx_types.h#L54-L68[they are constants].

You can see that some programs (like `aplay`) label the first hdmi port as `HDMI 1` whereas others (like `tvservice`) label it as `HDMI 0`. A little confusing, but oh well.

Now let's put all this together to play two videos in sync with omxplayer:
....
% cat sync_test_720p.mkv | tee >(omxplayer -o alsa:default:CARD=b1 --display 2 --no-keys pipe:0) >(omxplayer -o alsa:default:CARD=b2 --display 7 --no-keys pipe:0) >/dev/null
....
We have working synchronized video playing with sound outputting through both TVs! With this method, CPU usage is around 10% playing both videos (although once I saw it constantly pegged at 100% for the second omxplayer process??).

##### With native HDMI sound
As mentioned above, the latest version of omxplayer does not natively support outputting audio through the raspberry pi 4's second hdmi output. Indeed, if you try to specify an hdmi port number in omxplayer's sound output option, you get an error:
....
% omxplayer -o hdmi0 sync_test_1080p.mkv
Bad argument for -o: Output device must be `local', `hdmi', `both' or `alsa'
....
But, if we build a fork of omxplayer, we can unlock this feature. A https://www.raspberrypi.org/forums/viewtopic.php?t=258647#p1578284[raspberry pi engineer commented that omxplayer has not been updated to support sound on the second hdmi port of the raspberry pi 4], so he made a https://github.com/popcornmix/omxplayer/pull/754[pull request to add this feature]. Unfortunately, as https://github.com/popcornmix/omxplayer#readme[omxplayer is now deprecated], this pull request has not been merged. We can build it ourselves though with link:../install/build_omxplayer.sh[this omxplayer build script].

After building this version of omxplayer, you can check that omxplayer is now a newer version (your "Build date" may be different):
....
% omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Sat, 17 Apr 2021 06:26:28 +0100
        Version   : 1f1d0cc [master]
        Repository: https://github.com/popcornmix/omxplayer.git
....

Whereas before building this fork of omxplayer, your version output likely looked like this (if installed via `sudo apt install omxplayer`):
....
% omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 01 Aug 2019 12:50:43 +0000
        Version   : f543a0d [master]
        Repository: https://github.com/popcornmix/omxplayer.git
....

Now we can play two videos in sync with omxplayer, with sound outputting through both TVs:
....
% cat sync_test_720p.mkv | tee >(omxplayer -o hdmi0 --display 2 --no-keys pipe:0) >(omxplayer -o hdmi1 --display 7 --no-keys pipe:0) >/dev/null
....
With this method, CPU usage is around 5% playing both videos.

### vlc
Due to our cropping needs, link:cropping_videos_for_streaming_playback.adoc[vlc is not the preferred software to use for videoplayback in this project].

vlc may be installed via:
....
% sudo apt -y install vlc
....

#### One TV per raspberry pi

##### HDMI video output
This will play video with sound through the raspberry pi's first hdmi output.
....
% cvlc sync_test_1080p.mkv
....

##### Composite video output
....
% cvlc sync_test_1080p.mkv
....

Note: comparing composite vlc output to HDMI vlc output through the HDMI to RCA converter, the former stretches the screen if the aspect ratio differs. The sync test "circles" were slightly too tall through composite output!

#### Two TVs per raspberry pi
As with omxplayer, we can use https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture[ALSA] to route the sound. I am not aware of any non-ALSA sound routing methods for using both hdmi ports with VLC.
....
% cat sync_test_720p.mkv | tee >(cvlc - --mmal-display hdmi-1 -A alsa --alsa-audio-device default:CARD=b1) >(cvlc - --mmal-display hdmi-2 -A alsa --alsa-audio-device default:CARD=b2) >/dev/null
....
Somewhat anecdotally, sometimes this method would result in the two vlc players being slightly out of sync with each other (half a second or so). This happened maybe one in every ten attempts. With this method, CPU usage is around 15-25% playing both videos.

### gstreamer
Potentially gstreamer could be an option. See https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=309723[my forum post]. And link:cropping_videos_for_streaming_playback.adoc#alternatives[more info in our docs].