# TV output options
:toc:
:toclevels: 5

## HDMI video output options
### One vs two TVs per receiver raspberry pi
The raspberry pi 4 has two hdmi outputs. Thus, we could conceivably connect up to two TVs per receiver raspberry pi. There are pros and cons of connecting one vs two TVs per raspberry pi.

Using two TVs per raspberry pi allows you purchase fewer raspberry pis to control your TVs.

Using two TVs per raspberry pi means we will only be able to work with link:video_formats_and_hardware_acceleration.adoc#video-resolution[720p video at best] when playing two videos, whereas with one TV per raspberry pi, we can work with up to 1080p video.

### HDMI config options
If your HDMI display's resolution was not automatically detected (I use a https://amzn.to/3wWHE7T[HDMI to RCA converter] to power CRT TVs -- the resolution of my TVs was not automatically properly detected, perhaps because of the use of this converter), you may need to edit `/boot/config.txt`.

In my case, I had to add stanzas for `hdmi_group` and `hdmi_mode` (https://www.raspberrypi.org/documentation/configuration/config-txt/video.md[docs]):
....
hdmi_group:0=1
hdmi_group:1=1
hdmi_mode:0=1
hdmi_mode:1=1
....
After doing this, the TVs displayed the correct resolution. Whether you need to add these stanzas and if so, what their values should be, may vary depending on what sort of TVs you are using and if you have any HDMI to RCA converters in your signal path. See these https://www.raspberrypi.org/documentation/configuration/hdmi-config.md[raspberry pi docs for more info about what hdmi modes your device supports].

## Composite video output options
The raspberry pi also supports link:img/composite_video.jpg[composite video] (a.k.a "RCA video") via a https://www.adafruit.com/product/2881[cable like this]. As the raspberry pi only has one composite output, this option only allows you to control one TV per raspberry pi. If you are creating a CRT TV wall, I'd recommend using the composite output rather than using the HDMI output(s) combined with HDMI to composite converters. You don't actually end up saving very much money by using the two HDMI outputs to control two CRT TVs per raspberry pi after you account for the price of the https://amzn.to/3wWHE7T[HDMI to RCA converter], https://amzn.to/3gyUaoj[micro HDMI cables], and extra https://amzn.to/3tNCVmJ[USB power bank] that you will likely want to power all of the HDMI to RCA converters. Additional raspberry pi's are pretty cheap, and as mentioned above, using one TV per raspberry pi allows you to work with higher quality 1080p video.

To enable composite video output on a raspberry pi 4B, be sure to add `enable_tvout=1` to your `/boot/config.txt`. Note: the https://www.raspberrypi.org/documentation/configuration/config-txt/video.md[docs] say that enabling composite video output "slightly slows down the entire system".

There are a couple of additional composite https://www.raspberrypi.com/documentation/computers/config_txt.html#composite-video-mode[video output options] you may want to adjust.

1. If you're not using NTSC TVs, you'll want to adjust `sdtv_mode` (most North American TVs use NTSC)
1. If you have a CRT with a non-standard aspect ratio, you'll want to adjust `sdtv_aspect`

## Mixing and matching video output types
Note that you cannot use both a composite TV output and an HDMI TV output on the same raspberry pi. Enabling composite output requires setting `enable_tvout=1` in `/boot/config.txt`. HDMI TVs are not recognized when this setting is enabled, and composite TVs are not recognized when it is disabled.

Furthermore, be careful of using both composite output and HDMI output on different raspberry pis as part of the same TV wall. In my experience, the composite output will be very slightly out of sync with the HDMI output. The degree to which they are out of sync is very slight, so it may be tolerable, depending on your taste. I am not sure why they are slightly out of sync. Perhaps it has to do with using different clock speeds?

## General video options
These video options apply to both HDMI and composite video output.

When displaying video, you may notice https://www.raspberrypi.org/documentation/configuration/raspi-config.md#underscan[overscan / underscan] issues. Overscan settings may be adjusted via the https://www.raspberrypi.com/documentation/computers/config_txt.html#disable_overscan[`overscan_{left,right,top,bottom}` options] in `/boot/config.txt`. Note that these settings do not appear to apply to video players like omxplayer or vlc https://github.com/huceke/omxplayer/issues/103[unless you also set `overscan_scale=1`]. But enabling `overscan_scale` comes with a warning: "it can reduce image quality". Indeed, we see increased screen flicker when enabling `overscan_scale`. Thus it is debatable whether it is worth it to enable -- you trade a misaligned picture for a flickering picture.

In anecdotal testing, I have found that when using CRT TVs, I have slightly better aligned pictures when using the raspberry pi's HDMI output via an HDMI to RCA converter than when using the raspberry pi's composite video output.

For more on video calibration, see link:tv_calibration.adoc[the tv calibration docs].

## Video players
The below demonstrations use the following test videos (also https://www.youtube.com/watch?v=ucZl6vQ_8Uo[available on youtube]):
....
% youtube-dl https://www.youtube.com/watch\?v\=ucZl6vQ_8Uo -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio' --merge-output-format mkv -o sync_test_1080p.mkv
% youtube-dl https://www.youtube.com/watch\?v\=ucZl6vQ_8Uo -f 'bestvideo[vcodec^=avc1][height=720]+bestaudio' --merge-output-format mkv -o sync_test_720p.mkv
....
The conversion from mp4 to mkv container format is necessary because mp4 apparently isn't the best streaming container format (necessary when playing videos through pipes):
....
[mp4 @ 0xd6c0a0] muxer does not support non seekable output
....

### https://github.com/popcornmix/omxplayer/[omxplayer]
Due to our cropping needs, link:cropping_videos_for_streaming_playback.adoc[omxplayer is the preferred software to use for videoplayback in this project].

omxplayer may be installed via:
....
% sudo apt -y install omxplayer
....

#### One TV per raspberry pi

##### HDMI video output
This will play video with sound through the raspberry pi's first hdmi output.
....
% omxplayer -o hdmi sync_test_1080p.mkv
....

##### Composite video output
....
% omxplayer -o local sync_test_1080p.mkv
....

Note: comparing composite output to HDMI output through the HDMI to RCA converter, the composite output images are bigger because the composite output image overlaps the edges of the screen due to overscan.

#### Two TVs per raspberry pi

##### With ALSA sound
The latest version of omxplayer https://www.raspberrypi.org/forums/viewtopic.php?t=258647#p1578284[does not natively support outputting audio through the raspberry pi 4's second hdmi output]. As an alternative, we can rely on https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture[ALSA] to route the audio via omxplayer's `-o` option. Furthermore, we must now specify which hdmi port each omxplayer process will output through via omxplayer's `--display` option.

First, let's determine the ALSA device identifiers to use:
....
% aplay -L
...
default:CARD=b1
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Default Audio Device
...
default:CARD=b2
    bcm2835 HDMI 2, bcm2835 HDMI 2
    Default Audio Device
...
....

Next, let's determine the display numbers to use:
....
% tvservice -l
2 attached device(s), display ID's are :
Display Number 2, type HDMI 0
Display Number 7, type HDMI 1
....
These shouldn't change, because https://github.com/raspberrypi/userland/blob/3fd8527eefd8790b4e8393458efc5f94eb21a615/interface/vmcs_host/vc_dispmanx_types.h#L54-L68[they are constants].

You can see that some programs (like `aplay`) label the first hdmi port as `HDMI 1` whereas others (like `tvservice`) label it as `HDMI 0`. A little confusing, but oh well.

Now let's put all this together to play two videos in sync with omxplayer:
....
% cat sync_test_720p.mkv | tee >(omxplayer -o alsa:default:CARD=b1 --display 2 --no-keys pipe:0) >(omxplayer -o alsa:default:CARD=b2 --display 7 --no-keys pipe:0) >/dev/null
....
We have working synchronized video playing with sound outputting through both TVs! With this method, CPU usage is around 10% playing both videos (although once I saw it constantly pegged at 100% for the second omxplayer process??).

##### With native HDMI sound
As mentioned above, the latest version of omxplayer does not natively support outputting audio through the raspberry pi 4's second hdmi output. Indeed, if you try to specify an hdmi port number in omxplayer's sound output option, you get an error:
....
% omxplayer -o hdmi0 sync_test_1080p.mkv
Bad argument for -o: Output device must be `local', `hdmi', `both' or `alsa'
....
But, if we build a fork of omxplayer, we can unlock this feature. A https://www.raspberrypi.org/forums/viewtopic.php?t=258647#p1578284[raspberry pi engineer commented that omxplayer has not been updated to support sound on the second hdmi port of the raspberry pi 4], so he made a https://github.com/popcornmix/omxplayer/pull/754[pull request to add this feature]. Unfortunately, as https://github.com/popcornmix/omxplayer#readme[omxplayer is now deprecated], this pull request has not been merged. We can build it ourselves though with link:../install/build_omxplayer.sh[this omxplayer build script].

After building this version of omxplayer, you can check that omxplayer is now a newer version (your "Build date" may be different):
....
% omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Sat, 17 Apr 2021 06:26:28 +0100
        Version   : 1f1d0cc [master]
        Repository: https://github.com/popcornmix/omxplayer.git
....

Whereas before building this fork of omxplayer, your version output likely looked like this (if installed via `sudo apt install omxplayer`):
....
% omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 01 Aug 2019 12:50:43 +0000
        Version   : f543a0d [master]
        Repository: https://github.com/popcornmix/omxplayer.git
....

Now we can play two videos in sync with omxplayer, with sound outputting through both TVs:
....
% cat sync_test_720p.mkv | tee >(omxplayer -o hdmi0 --display 2 --no-keys pipe:0) >(omxplayer -o hdmi1 --display 7 --no-keys pipe:0) >/dev/null
....
With this method, CPU usage is around 5% playing both videos.

#### Note on using alsa sound
By default, omxplayer does not use alsa sound. Thus the "normal" raspberry pi volume controls (`alsamixer`, `amixer`, etc) have no effect on omxplayer's volume. See the https://www.raspberrypi.org/documentation/usage/audio/README.md[documentation here]:
____
Note that omxplayer doesn't use ALSA and so ignores the audio configuration set by raspi-config or amixer.
____

Omxplayer does have options to use alsa sound output as discussed in the section above "With ALSA sound". Alsa sound can also be used in the composite TV output setup by specifying:
....
% omxplayer -o alsa:hw:0,0 sync_test_1080p.mkv
....

Most of the time, the alsa sound works fine. But in some videos, I have noticed occasional playback issues when using alsa sound -- sometimes one or more TVs would freeze when attempting to play the video, resulting in a frozen image of one of the first few frames of the video. Meanwhile, the rest of the TVs would continue playing the video. Thus, I do not recommend using alsa sound output. I noticed these alsa playback glitches when testing on https://www.youtube.com/watch?v=4S5KBlieT0I[this video] while using composite TV output. I noticed playback glitches in 3 out of 9 tests that I ran in this manner.

UPDATE 2021-11-17: I tried using alsa sound again. One benefit of alsa sound is that volume changes would be much more responsive -- it's faster to change the volume via setting system volume than by sending volume messages to omxplayer via dbus. When using alsa sound, playback would be jittery / freeze for about one second at the start of every video. This is tolerable, because it syncs back up shortly. But when playing silent videos (like https://www.youtube.com/watch?v=-pdVUsCqd2U[dvd bounce]), I noticed that perhaps one out of every 3 - 5 plays, the videoplayback is not perfectly in sync amongst all TVs (tested with a 10 TV wall setup). Some of the TVs would be perhaps 100 to 200 ms out of sync. This is most noticeable when the DVD logo bounces off a wall while spanning multiple TVs. One of the neighboring TVs will see the logo change direction sooner than the other. You can also notice it when in DISPLAY_MODE_TILE and noticing how some TVs see the "bounce" slightly earlier. See the https://github.com/dasl-/piwall2/tree/volume[volume branch] where I implemented these alsa sound changes (but I did not merge them back to main).

### vlc
Due to our cropping needs, link:cropping_videos_for_streaming_playback.adoc[vlc is not the preferred software to use for videoplayback in this project].

vlc may be installed via:
....
% sudo apt -y install vlc
....

#### One TV per raspberry pi

##### HDMI video output
This will play video with sound through the raspberry pi's first hdmi output.
....
% cvlc sync_test_1080p.mkv
....

##### Composite video output
....
% cvlc sync_test_1080p.mkv
....

Note: comparing composite vlc output to HDMI vlc output through the HDMI to RCA converter, the former stretches the screen if the aspect ratio differs. The sync test "circles" were slightly too tall through composite output!

#### Two TVs per raspberry pi
As with omxplayer, we can use https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture[ALSA] to route the sound. I am not aware of any non-ALSA sound routing methods for using both hdmi ports with VLC.
....
% cat sync_test_720p.mkv | tee >(cvlc - --mmal-display hdmi-1 -A alsa --alsa-audio-device default:CARD=b1) >(cvlc - --mmal-display hdmi-2 -A alsa --alsa-audio-device default:CARD=b2) >/dev/null
....
Somewhat anecdotally, sometimes this method would result in the two vlc players being slightly out of sync with each other (half a second or so). This happened maybe one in every ten attempts. With this method, CPU usage is around 15-25% playing both videos.

### gstreamer
Potentially gstreamer could be an option. See https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=309723[my forum post]. And link:cropping_videos_for_streaming_playback.adoc#alternatives[more info in our docs].

## Video rotation
The piwall2 project supports rotating TVs in multiples of 90 degrees. Thus, you can have a TV that is physically sideways or upside down, but still displaying a "right-side-up" video image. At first, I tried to accomplish this via `omxplayer` 's `--orientation` flag:

....
% omxplayer --help
...
    --orientation n         Set orientation of video (0, 90, 180 or 270)
....

Using this almost worked, but over time, the video playback would get out of sync for any TV that was rotated. Playback on rotated TVs was slower than on non-rotated TVs. In particular, I found my videos would get approximately one second out of sync for every minute of playback or so. How quickly things got out of sync might also depend on the video resolution -- higher resolution videos would get out of sync more quickly. Perhaps this is because the raspberry pi has to actually do a non-insignificant amount of work to rotate a video (see https://forums.raspberrypi.com/viewtopic.php?t=248353[this forum thread]).

To get around this playback speed sync issue, I tried adjusting playback speed via `omxplayer` 's https://github.com/popcornmix/omxplayer/#rate-rw[DBUS API], but this proved to be a losing battle. As the amount of lag seemed to vary with video resolution, I'd need to calculate lag compensation amounts for an endless number of video resolution permutations. I tried investigating `omxplayer` 's https://github.com/dasl-/piwall2/blob/main/docs/configuring_omxplayer.adoc#live[`--live` option again]. This actually sort of worked, but the jankiness we've seen in the past when using this option continued. Sound was full of static, and occasionally there would be video glitch artifacts (green screens, slight sync issues, etc).

The next thing I tried was setting the rotation via `/boot/cmdline.txt` as https://www.raspberrypi.com/documentation/computers/configuration.html#command-line-options[documented here]. In particular, I tried using this:

....
console=serial0,115200 console=tty1 root=PARTUUID=5a99a147-02 rootfstype=ext4 elevator=deadline fsck.repair=yes video=Composite-1:720x480@60i,margin_left=32,margin_right=32,margin_top=32,margin_bottom=32,rotate=90 rootwait
....

This had the same playback sync issues, losing about a second of synchronization per minute of playback.

Finally, I tried something suggested on a https://forums.raspberrypi.com/viewtopic.php?t=247619#p1691517[forum post]. I commented out the line `dtoverlay=vc4-fkms-v3d` in conjunction with adding a line `display_hdmi_rotate=3` in `/boot/config.txt`. More https://forums.raspberrypi.com/viewtopic.php?p=1507622#p1507247[details] about what this might do. I believe that this means I will be using the https://www.raspberrypi.com/documentation/computers/configuration.html#legacy-graphics-driver["legacy" graphics driver]. See https://forums.raspberrypi.com/viewtopic.php?t=317511[this thread] with more details about graphics driver stuff. Note also that I am using https://www.raspberrypi.com/documentation/computers/config_txt.html#display_hdmi_rotate[`display_hdmi_rotate`], despite using composite TV output. It works (shrug)! Note that using the deprecated https://www.raspberrypi.com/documentation/computers/config_txt.html#display_rotate[`display_rotate`] also worked, but using https://www.raspberrypi.com/documentation/computers/config_txt.html#display_lcd_rotate[`display_lcd_rotate`] did not rotate anything in my composite TV output setup. This combination of settings actually worked -- playback did not suffer from lag / sync issues over time when the display was rotated in this manner. Strangely, https://forums.raspberrypi.com/viewtopic.php?t=248353#p1523594[this forum post] suggests that using the `display_rotate` flags should be more work / slower... but somehow they solved my lag problem.

### Note on OS support
link:pass:[raspberry pi - Troubleshooting KMS HDMI output.pdf][Reference]

https://pip.raspberrypi.com/categories/685-whitepapers-app-notes/documents/RP-004341-WP/Troubleshooting-KMS-HDMI-output.pdf[dead link reference, mirrored in link above]

* Buster: In buster, the default graphics stack is FKMS. In order to use the legacy graphics stack, we must comment out `dtoverlay=vc4-fkms-v3d`
* Bullseye (successor to Buster): In bullseye, the default graphics stack is KMS. In order to use the legacy graphics stack, we must comment out `dtoverlay=vc4-kms-v3d`
* Bookworm (successor to Bullseye): In bookworm, only the KMS graphics stack is supported. Neither FKMS nor legacy graphics stacks work. Thus, bookworm is incompatible (AFAIK) with performant screen rotation.

As a final test, I tried another option: using the legacy graphics driver by commenting out `dtoverlay=vc4-fkms-v3d` in `/boot/config.txt`, but performing the rotation via `omxplayer` 's `--rotate` flag. This suffered from the same playback lag issues as before.

So the only method of rotation that worked without lag was doing the rotation at the OS level, by setting options in `/boot/config.txt`. I believe that this means if you wanted to use two TVs per raspberry pi, both TVs would need to share the same rotation settings. You could not have one TV rotated and one TV not rotated.

One interesting thing to note: using my successful method of rotation (commenting out the line `dtoverlay=vc4-fkms-v3d` in conjunction with adding a line `display_hdmi_rotate=3` in `/boot/config.txt`), I found that omxplayer added black letterbox bars on the top and bottom of the screen when playing a video. For some reason, omxplayer didn't seem to realize how big the screen was? My only hypothesis here is a difference in obscure kernel settings. When rotating the screen in this manner, here is the output of https://www.raspberrypi.com/documentation/computers/configuration.html#the-kernel-command-line[`/proc/cmdline`]:

....
% cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=416 bcm2708_fb.fbheight=656 bcm2708_fb.fbswap=1 smsc95xx.macaddr=DC:A6:32:C0:A5:BC vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=5a99a147-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
....

Whereas on a receiver without any rotation settings applied, here is the output:
....
% cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=Composite-1:720x480@60i,margin_left=32,margin_right=32,margin_top=32,margin_bottom=32 smsc95xx.macaddr=DC:A6:32:B6:A3:34 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=2586a590-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
....

Note that `656 + 32 + 32 = 720`, and `416 + 32 + 32 = 480`. I'm not sure if this is relevant though. Regardless, making use of `omxplayer` 's `--aspect-mode` option solved the problem:

....
% omxplayer --help
...
    --aspect-mode type      Letterbox, fill, stretch. Default: stretch if win is specified, letterbox otherwise
....

In particular, I set `--aspect-mode stretch`, whereas before I was not making use of the `--aspect-mode` option at all, thus defaulting to `letterbox`. This should be fine, because in all cases we are setting an explicit crop window for the video via the `--crop` flag. We always ensure that the passed crop window matches the TVs aspect ratio exactly, thus stretching should have no effect, except in this weird edge case where it actually solves a problem. I confirmed that a video of a circle is correctly proportioned when using this `--aspect-mode stretch` flag, both on rotated displays and unrotated displays. Without the `--aspect-mode stretch` flag, a circle was distorted on the rotated display. This was a good https://www.youtube.com/watch?v=d-z6LOGwOj4[test video] for this case.
